# Shell variables
# Generated by 'wal'
wallpaper='/home/jonathan/dotfiles/i3/wall13.png'

# Special
background='#fdfbfb'
foreground='#413E5F'
cursor='#413E5F'

# Colors
color0='#fdfbfb'
color1='#EFB2B9'
color2='#B0B6CF'
color3='#D1B9C7'
color4='#F1BCC2'
color5='#BBC3DB'
color6='#AFD5F8'
color7='#413E5F'
color8='#928a8c'
color9='#EFB2B9'
color10='#B0B6CF'
color11='#D1B9C7'
color12='#F1BCC2'
color13='#BBC3DB'
color14='#AFD5F8'
color15='#413E5F'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
